services:
  mariadb:
    build:
      dockerfile: ./dc/.container/db/Dockerfile
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MARIADB_DATABASE: '${DB_DATABASE}'
      #MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
      MARIADB_ALLOW_EMPTY_PASSWORD: 1
      TZ: '${APP_TIMEZONE}'
    volumes:
      - ./dc/.container/db/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
      - ./dc/.container/db/data:/var/lib/mysql
    networks:
      - tt-hub
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    ports:
      - 8080:80
    environment:
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
      PMA_HOST: mariadb
    networks:
      - tt-hub
    depends_on:
      mariadb:
        condition: service_healthy

  php:
    build:
      dockerfile: './dc/.container/php/Dockerfile'
    volumes:
      - './:/var/www/html'
    networks:
      - tt-hub
    ports:
      - '5173:5173'
    depends_on:
      mariadb:
        condition: service_healthy

  web:
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: './dc/.container/web/Dockerfile'
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - '80:80'
    # src配下のファイルをコンテナ内の~/va/www/html配下に配置
    volumes:
      - './:/var/www/html'
    networks:
      - tt-hub
    depends_on:
      - php
      - mariadb
      - phpmyadmin
      - mailpit

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - tt-hub

  redoc:
    image: redocly/redoc
    environment:
      - SPEC_URL=docs/index.yaml
    volumes:
      - ./documents/api/:/usr/share/nginx/html/docs
    ports:
      - '3032:80'

networks:
  tt-hub:
    driver: bridge
